### ISSUE TITLE
Demo image series DESS folders

### ISSUE THREAD

**Issue by FroylanZR** [sbonaretti/pyKNEEr#11]
Hello, i have a question regarding the demo datasets provided with pykneer. 

On the pykneer website you say these are the files:
![image](https://user-images.githubusercontent.com/17280713/114240009-b1cc2b80-993b-11eb-9803-aec6075915a7.png)

DESS has folders 01 and 02, and CubeQuant has 01, 02, 03 and 04, i would like to know what is the difference between these datasets, between DESS 01 and DESS 02 for example.

As i understand, they all come from the same patient/subject (01), is that right?

**Comment by sbonaretti** [comment]
Hi,
Yes, they all belong to the same subjects. The two DESS volumes are needed to calculate T2 whereas the four CubeQuant volumes are used to calculate T1rho. I am not very strong in image acquisition, as I deal more with image processing. So I am not sure I can tell you more about these two acquisition techniques! If you want to know more, a good review paper can be this one: https://pubmed.ncbi.nlm.nih.gov/31755191/ 
Hope this helps!
Serena
