### ISSUE TITLE
Error in read_dicom_stack from preprocessing.ipynb

### ISSUE THREAD

**Issue by ghost** [sbonaretti/pyKNEEr#12]
Hi Serena

I am trying to run the pykneer preprocessing but I am receiving this error message when I try to run prep.read_dicom_stack from preprocessing.ipynb: 

RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: D:\a\1\sitk-build\ITK\Modules\IO\Meta\src\itkMetaImageIO.cxx:1129:
itk::ERROR: itk::ERROR: MetaImageIO(000002792F74B1C0): File cannot be written: .\preprocessed\01/DESS/01_temp.mha
Reason: No such file or directory

Thank you,

**Comment by sbonaretti** [comment]
Hi! 
This can be due to the fact that in your file names `\ `and `/` are mixed: `.\preprocessed\01/DESS/01_temp.mha` 
If you are on a Windows, you might need to substitute all `/` to `\`. 
Let me know if this solves the issue!
