### ISSUE TITLE
Error in: Segment Bone

### ISSUE THREAD

**Issue by CDiazCuadro** [sbonaretti/pyKNEEr#15]
Hello Serena,
I am trying to use (an eventually extend to the tibia) pykneer as part of my PhD.
Currently, I have been running the demo_v4 with some issues that I figured out how to fix them. (A matter of versions, etc).
However, right now i am stuck on **Segment Bone - Part 1**
Exactly when we call "segm.register_bone_to_reference(image_data, n_of_cores)".

Following is the error msj showed by the jupyter Lab:

-------------------------------------------------------------------------------------------
ERROR: No output created in bone.rigid()
-------------------------------------------------------------------------------------------
`/home/cdiaz/.local/lib/python3.8/site-packages/pykneer/elastix/Linux/elastix:` error while loading shared libraries: libANNlib.so: cannot open shared object file: No such file or directory
`/home/cdiaz/.local/lib/python3.8/site-packages/pykneer/elastix/Linux/elastix:` error while loading shared libraries: libANNlib.so: cannot open shared object file: No such file or directory

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/cdiaz/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cdiaz/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/cdiaz/.local/lib/python3.8/site-packages/pykneer/segmentation_sa_for_nb.py", line 117, in register_bone_to_reference_s
    bone.rigid     (image_data)
  File "/home/cdiaz/.local/lib/python3.8/site-packages/pykneer/elastix_transformix.py", line 214, in rigid
    print ("-> elastix not installed. Error message is: " + output)
TypeError: can only concatenate str (not "int") to str
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 segm.register_bone_to_reference(image_data, n_of_cores)

File ~/.local/lib/python3.8/site-packages/pykneer/segmentation_sa_for_nb.py:133, in register_bone_to_reference(all_image_data, n_of_processes)
    131 start_time = time.time()
    132 pool = multiprocessing.Pool(processes=n_of_processes)
--> 133 pool.map(register_bone_to_reference_s, all_image_data)
    134 print ("-> Registration completed")
    135 print ("-> The total time was %.2f seconds (about %d min)" % ((time.time() - start_time), (time.time() - start_time)/60))

File ~/anaconda3/lib/python3.8/multiprocessing/pool.py:364, in Pool.map(self, func, iterable, chunksize)
    359 def map(self, func, iterable, chunksize=None):
    360     '''
    361     Apply `func` to each element in `iterable`, collecting the results
    362     in a list that is returned.
    363     '''
--> 364     return self._map_async(func, iterable, mapstar, chunksize).get()

File ~/anaconda3/lib/python3.8/multiprocessing/pool.py:771, in ApplyResult.get(self, timeout)
    769     return self._value
    770 else:
--> 771     raise self._value

TypeError: can only concatenate str (not "int") to str

Could you give me some ideas about which could be the problem here?

Thank you in advance!

**Comment by sbonaretti** [comment]
Hi! 
The issue is that pyKNEEr cannot find the Elastix libraries: `error while loading shared libraries: libANNlib.so: cannot open shared object file: No such file or directory`. Elastix (https://elastix.lumc.nl/) is a software for registration, and pyKNEEr uses it for the atlas-based segmentation. When you install pyKNEEr, you should automatically download the Elastix libraries in the folder `/home/cdiaz/.local/lib/python3.8/site-packages/pykneer/elastix/Linux/elastix`. I am not super familiar with linux, but my guess is that you might have to add this path to the environmental variables of your machine, or something similar. Let me know if this works!
