### ISSUE TITLE
error when running segm.prepare_reference(image_data)

### ISSUE THREAD

**Issue by xiaohech** [sbonaretti/pyKNEEr#7]
Hi,

I extracted some images in OAI dataset on my Windows PC and successfully finished the preprocessing steps and got the file 10512117_prep.mha.
Then I encountered the following error when I ran segm.prepare_reference(image_data) in the segmentation procedure.
Do you know what caused this issue?

Thanks!

Here's my file image_list_newsubject.txt.
.\reference\newsubject
.\preprocessed\
r reference.mha
m 10512117_prep.mha

Here's the error message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-59-657d0eec349c> in <module>
----> 1 segm.prepare_reference(image_data)

C:\ProgramData\Anaconda3\lib\site-packages\pykneer\segmentation_sa_for_nb.py in prepare_reference(all_image_data)
     70         image_data["current_anatomy"] = image_data["bone"]
     71         bone = elastix_transformix.bone()
---> 72         bone.prepare_reference (image_data)
     73 
     74         # instanciate cartilage class and prepare reference

C:\ProgramData\Anaconda3\lib\site-packages\pykneer\elastix_transformix.py in prepare_reference(self, image_data)
     92         if not os.path.isfile(reference_mask_dil_name):
     93             mask    = sitk.ReadImage(reference_mask_name)
---> 94             maskDil = sitkf.dilate_mask(mask, radius)
     95             sitk.WriteImage(maskDil, reference_mask_dil_name)
     96 

C:\ProgramData\Anaconda3\lib\site-packages\pykneer\sitk_functions.py in dilate_mask(mask, radius)
    353     # dilate reference binary mask
    354     mask     = sitk.Cast(mask,sitk.sitkInt16) # make sure that input of BinaryDilate is int
--> 355     mask_dil = sitk.BinaryDilate(mask,radius)
    356 
    357     return mask_dil

C:\ProgramData\Anaconda3\lib\site-packages\SimpleITK\SimpleITK.py in BinaryDilate(*args, **kwargs)
   7604 def BinaryDilate(*args, **kwargs):
   7605     r"""BinaryDilate(Image image1, VectorUInt32 kernelRadius=std::vector< uint32_t >(3, 1), itk::simple::KernelEnum kernelType=sitkBall, double backgroundValue=0.0, double foregroundValue=1.0, bool boundaryToForeground=False) -> Image"""
-> 7606     return _SimpleITK.BinaryDilate(*args, **kwargs)
   7607 class BinaryErodeImageFilter(ImageFilter):
   7608     r"""Proxy of C++ itk::simple::BinaryErodeImageFilter class."""

TypeError: in method 'BinaryDilate', argument 2 of type 'std::vector< unsigned int,std::allocator< unsigned int > >'

**Comment by sbonaretti** [comment]
Hi!

Do you have the files `reference_f.mha` and `reference_fc.mha` in the folder  `.\reference\newsubject? When you open them in some software, e.g. [Itk-snap](http://www.itksnap.org/pmwiki/pmwiki.php), do they look fine?

**Comment by olegshagalov** [comment]
Hi!

I have the same problem. The mentioned files are in newsubject folder but they do not open neither editor, nor notepad. pyKNEEr version is 0.0.5

**Comment by sbonaretti** [comment]
Hi! 

Could you try to downgrade SimpleITK to version 1.1.0? 

Let me know if that works!
Serena

**Comment by twaungana** [comment]
Hi,

I also encountered this issue - did downgrading to version 1.1.0 work?

**Comment by sbonaretti** [comment]
Issue should be solved with version 0.0.6.3
